export OMP_NUM_THREADS=4
export VLLM_CPU_OMP_THREADS_BIND=nobind
export VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS=1200

export USER_VLLM_LOGGING_LEVEL="DEBUG"
# export USER_VLLM_LOGGING_LEVEL="INFO"
# export VLLM_USE_MODELSCOPE=True
# export MODELSCOPE_CACHE="/modelscope/hub"
